version: '3'

tasks:
  run:
    cmd: go run ./cmd/clear-carrot/

  build:
    cmds: 
      - docker build . -t clear-carrot
      - docker run --rm -d -p 0:8000 clear-carrot

  tidy:
    cmds:
      - go mod tidy
      - go fmt ./...
    silent: true
  
  htmx:
    cmds:
      - curl -L -o static/htmx.min.js https://unpkg.com/htmx.org@latest/dist/htmx.min.js
      - curl -L -o static/hyperscript.min.js https://unpkg.com/hyperscript.org@latest/dist/_hyperscript.min.js